from tkinter import *
root=Tk()
mymenu=Menu(root)
root.config(menu=mymenu)
submenu=Menu(mymenu)
mymenu.add_cascade(label="file",menu=submenu)
submenu.add_command(label="new text file")
submenu.add_command(label="new file")
submenu.add_command(label="new window")
submenu.add_separator()
submenu.add_command(label="open file")
submenu.add_command(label="open folder")

newmenu=Menu(mymenu)
mymenu.add_cascade(label="edit",menu=newmenu)
newmenu.add_command(label="undo")
newmenu.add_command(label="redo")
newmenu.add_separator()
newmenu.add_command(label="cut")
newmenu.add_command(label="copy")
newmenu.add_command(label="paste")

three=Menu(mymenu)
three.add_command(label="open view")
three.add_command(label="run")
three.add_separator()
three.add_command(label="appearence")
mymenu.add_cascade(label="view",menu=three)
three.add_command(label="open view")
three.add_command(label="run")
three.add_separator()
three.add_command(label="appearence")

four=Menu(mymenu)
mymenu.add_cascade(label="go",menu=four)
four.add_command(label="back")
four.add_command(label="forward")
four.add_separator()
four.add_command(label="switch editor")

toolbar=Frame(root,bg="green")
bt=Button(toolbar,text="crop")
bt.pack(side=LEFT,padx=2,pady=2)
toolbar.pack(fill="x",side=TOP)


statusbar=Label(root,text="statusbar",bg="red")
statusbar.pack(fill="x",side=BOTTOM)

root.mainloop()
